package gcode

import (
	"bytes"
	"strings"
	"testing"
	"time"
)

func TestPatchGCodeTime(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "no G28 unchanged",
			in:   "; estimated printing time = 1h 2m\nG1 X1 Y1\n",
			want: "; estimated printing time = 1h 2m\nG1 X1 Y1\n",
		},
		{
			name: "insert TIME before first G28",
			in:   "; estimated printing time = 1h 2m 3s\nM104 S200\nG28\nG1 X1 Y1\n",
			want: "; estimated printing time = 1h 2m 3s\nM104 S200\n;TIME:3723\nG28\nG1 X1 Y1\n",
		},
		{
			name: "existing TIME not duplicated",
			in:   ";TIME:42\n; estimated printing time = 1h 2m 3s\nG28\n",
			want: ";TIME:42\n; estimated printing time = 1h 2m 3s\nG28\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := PatchGCodeTime([]byte(tt.in))
			if !bytes.Equal(got, []byte(tt.want)) {
				t.Fatalf("PatchGCodeTime() = %q, want %q", string(got), tt.want)
			}
		})
	}
}

func TestApplyTemperatureOverrides(t *testing.T) {
	input := strings.Join([]string{
		"; header M104 S150 is a comment",
		"M104 S150 ; low nozzle",
		"M104S150 ; compact low nozzle",
		"M109 S150.5",
		"M104 S0 ; cooldown stays off",
		"M140 S55",
		"M140S55",
		"M190 S65",
		"M140 S0 ; bed cooldown",
		"M104 S230 ; higher nozzle unchanged",
		"G1 X1 S150 ; non-temp command unchanged",
		"",
	}, "\n")
	want := strings.Join([]string{
		"; header M104 S150 is a comment",
		"M104 S210 ; low nozzle",
		"M104S210 ; compact low nozzle",
		"M109 S210",
		"M104 S0 ; cooldown stays off",
		"M140 S60",
		"M140S60",
		"M190 S65",
		"M140 S0 ; bed cooldown",
		"M104 S230 ; higher nozzle unchanged",
		"G1 X1 S150 ; non-temp command unchanged",
		"",
	}, "\n")

	got, stats := ApplyTemperatureOverrides([]byte(input), TemperatureOverrides{
		NozzleMinTempC: 210,
		BedMinTempC:    60,
	})

	if string(got) != want {
		t.Fatalf("ApplyTemperatureOverrides() = %q, want %q", string(got), want)
	}
	if stats.NozzleCommands != 3 || stats.BedCommands != 2 {
		t.Fatalf("stats = %+v, want nozzle=3 bed=2", stats)
	}
}

func TestExtractLayerCount(t *testing.T) {
	tests := []struct {
		name    string
		in      string
		want    int
		wantHas bool
	}{
		{
			name:    "OrcaSlicer LAYER_COUNT header",
			in:      ";LAYER_COUNT:42\n; generated by OrcaSlicer\nG28\n",
			want:    42,
			wantHas: true,
		},
		{
			name:    "PrusaSlicer LAYER_CHANGE fallback",
			in:      "; generated by PrusaSlicer\nG28\n;LAYER_CHANGE\nG1 X1\n;LAYER_CHANGE\n;LAYER_CHANGE\n",
			want:    3,
			wantHas: true,
		},
		{
			name:    "no markers",
			in:      "; generated by slicer\nG28\nG1 X1\n",
			want:    0,
			wantHas: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, ok := ExtractLayerCount([]byte(tt.in))
			if got != tt.want || ok != tt.wantHas {
				t.Fatalf("ExtractLayerCount() = (%d,%v), want (%d,%v)", got, ok, tt.want, tt.wantHas)
			}
		})
	}
}

// TestGCodeRegex_NoReDoS verifies that the package-level compiled regexps do
// not exhibit catastrophic backtracking (ReDoS) on adversarial user-controlled
// GCode file content (CodeQL #24 / CWE-1333).
//
// These patterns run on uploaded GCode files, so the inputs are user-controlled.
// Each test feeds a 1000-character worst-case string and asserts the match
// completes within 500 ms — exponential backtracking would exceed this by orders
// of magnitude.
func TestGCodeRegex_NoReDoS(t *testing.T) {
	const deadline = 500 * time.Millisecond

	tests := []struct {
		name    string
		pattern string // for documentation only; we call the pre-compiled vars
		input   func() string
		match   func(s string) bool
	}{
		{
			// estimatedTimePattern: `(?i);\s*estimated printing time[^=]*=\s*(.*)`
			// Worst-case: prefix almost-matches the literal then fails at '='.
			name:    "estimatedTimePattern adversarial",
			pattern: `(?i);\s*estimated printing time[^=]*=\s*(.*)`,
			input:   func() string { return "; estimated printing time" + strings.Repeat("x", 1000) },
			match:   func(s string) bool { return estimatedTimePattern.MatchString(s) },
		},
		{
			// timeTokenPattern: `(?i)(\d+)\s*([dhms])`
			// Worst-case: all digits, no trailing unit letter.
			name:    "timeTokenPattern adversarial",
			pattern: `(?i)(\d+)\s*([dhms])`,
			input:   func() string { return strings.Repeat("9", 1000) },
			match:   func(s string) bool { return timeTokenPattern.MatchString(s) },
		},
		{
			// layerCountPatterns[1]: `(?i)^;\s*total layer(?:s)?\s*(?:number|count)?\s*[=:]\s*(\d+)`
			// Worst-case: matches prefix up to the number anchor, then fails.
			name:    "layerCountPattern[1] adversarial",
			pattern: `(?i)^;\s*total layer(?:s)?\s*(?:number|count)?\s*[=:]\s*(\d+)`,
			input:   func() string { return ";total layers number count" + strings.Repeat(" ", 1000) },
			match:   func(s string) bool { return layerCountPatterns[1].MatchString(s) },
		},
		{
			// gcodeCommandPattern: `(?i)^\s*([A-Z]+\d+)`
			// Worst-case: long letter prefix with no digit.
			name:    "gcodeCommandPattern adversarial",
			pattern: `(?i)^\s*([A-Z]+\d+)`,
			input:   func() string { return strings.Repeat("M", 1000) },
			match:   func(s string) bool { return gcodeCommandPattern.MatchString(s) },
		},
		{
			// tempParamPattern: `(?i)(^|[ \t])S[ \t]*([-+]?[0-9]+(?:\.[0-9]+)?)`
			// Worst-case: valid S prefix followed by a long non-number suffix.
			name:    "tempParamPattern adversarial",
			pattern: `(?i)(^|[ \t])S[ \t]*([-+]?[0-9]+(?:\.[0-9]+)?)`,
			input:   func() string { return "S" + strings.Repeat("x", 1000) },
			match:   func(s string) bool { return tempParamPattern.MatchString(s) },
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			input := tc.input()
			done := make(chan bool, 1)
			go func() {
				done <- tc.match(input)
			}()
			select {
			case <-done:
				// completed within deadline — pass
			case <-time.After(deadline):
				t.Errorf("regexp %q took longer than %v on 1000-char adversarial input — possible ReDoS", tc.pattern, deadline)
			}
		})
	}
}
